---
title: Acuicultura Ecológica del Pejerrey (_Odontesthes bonariensis_) en Lagunas Pampásicas

output: ioslides_presentation
---


# objetivos del proyecto 

Optimizar los procesos de cultivo y cría de pejerrey ( _Odontesthes bonariensis_) teniendo en cuenta los conceptos de acuicultura ecológica, para incorporarlo a las redes productivas de la Región Pampeana. 

# La Acuicultura Ecológica

La _Acuicultura Ecológica_ es un modelo de cultivo de peces que integra aspectos **ambientales**, **sociales** y **económicos** dentro de un _enfoque ecosistémico_. 

Tres principios son fundamentales para ejercer esta actividad, a saber:  

1. Debe desarrollarse en el contexto de las funciones y servicios del ecosistema, sin degradarlo, más allá de la capacidad de resiliencia que éstos poseen.  

2. Debe ofrecer bienestar y equidad a todos los actores involucrados.  

3. Debe ser desarrollada e integrada a otros sectores relevantes del desarrollo político, económico, social y ambiental. 


# El Pejerrey ( _Odontesthes bonariensis_)

Es un pez originario de Argentina, Uruguay y sur del Brasil. Su distribucion incluye las cuencas del Río de la Plata, río Paraná, río Uruguay, cuenca del río Salado y las lagunas Pampeanas. 

Es una de las especies emblemáticas de la ictiofauna de Argentina. De gran importancia socio-económica, ya que es el sustento de actividades recreacionales, deportivas y comerciales.

Pez pelágico, ... que se alimenta principalmente de zooplancton, está característica es fundamental para el desarrollo de su cultivo en los ambientes seleccionados. 


# El cultivo de pejerrey ( _Odontesthes bonariensis_)

Esta especie ha sido identificada como de creciente interés en la acuicultura del país, debido a su importancia deportiva, recreacional, consumo y su alto valor simbólico en la región.

Los estudios e iniciativas sobre su aprovechamiento regional, de manera sustentable comenzaron hace más de cien años en la región pampeana y otras zonas del país. Este desarrollo, se orientó inicialmente a la producción de larvas, en cautiverio, las cuales han servido para el repoblamiento en ambientes naturales y artificiales.

El interés en la ampliación de su piscicultura, está orientado en esta oportunidad a la preduccion de juveniles  presenta  





# Las lagunas Encadenadas del Río Salado 

Este sistema incluye siete lagunas vinculadas por arroyos de escasa longitud, que finalmente desaguan en el Río Salado. Algunos de estos ambientes tienen características arréicas y un grado variable de permanencia del agua de acuerdo al desarrollo de sus cuencas y al ciclo hidrológico. Naturalmente fértiles y potencialmnete muy productivos. Gran parte de su alta productividad se debe a su localización sobre uno de los suelos más fértiles del planeta.

Son cuerpos de agua someros que presentan características compartidas ya que la mayoría tiene un tamaño superior a 100 ha, de carácter eutrófico a hipereutrófico, por lo general permanentes y muy pocas superan los 4 m de profundidad, siendo polimícticas principalmente por la acción del viento. 

Se trata de ambientes acuaticos que van de oligohalinos a mesohalinos, considerando la composición iónica de las lagunas pampeanas por lo general son bicarbonato-sódicas. 

Este proyecto se ejecuta en tres lagunas, a saber, **Laguna Salada de Monasterio**, **Laguna Vitel** y **Laguna San Lorenzo** que hacen parte de las **Lagunas Encadenadas del Río Salado**.

# Etapas del proyecto

El proyecto cuenta con varias fases, la primera de ellas es la evaluación de la calidad de agua, que permite establecer el inicio del cultivo.

Seguidamente se realiza la construcción de las jaulas, para esto es necesario la consecución de todos los elementos que conforman la estructura, al terminar su construcción éstas se instalan en las lagunas seleccionadas para el estudio.

Por ultimo se realiza la siembra de las larvas de pejerrey, actividad que se desarrolla cuando todo lo anteriormente señaladao, se ha realizado y evaluado. 


# Evaluacion de la calidad del agua

1. Parámetros fisicoquimicos como Temperatura, conductividad, oxigeno, ph, son monitoreados constantemente. Otros parámetros evaluados son el fósforo, también sustancias nitrogenadas  amonio, nitritos y nitratos.

2. Evaluación del zooplancton, consiste en determinar las especies, los principales grupos de zooplancton, la cantidad disponible; esto es uno de los aspectos fundamentales en el desarrollo de la acuicultura ecológica del pejerrey, ya que esta es la base de su alimentación durante su etapa de desarrollo (larval y juvenil) del pez.

# Construcción de las Jaulas

Es una activiad que trata de realizarse de manera grupal, de manera que sirva como taller de enseñaza a los interesados en la instalación de jaulas.  Aqui se reúnen los materiales (tablas, bulónes y otras piezas metálicas) necesarias para la construcción. 

# Instalación de las Jaulas en las lagunas

Consiste en el desplazamiento y ubicación de la estructura de la jaula dentro de la laguna. 

Para esta actividad es necesario identificar el mejor sitio dentro de la laguna y para logarlo es necesario tener en cuenta factores como profundidad, corrientes que se formen dentro del cuerpo de agua, ubicación respecto de la costa, etre otras.


# Siembra de larvas de pejerrey ( _Odontesthes bonariensis_) 

La siembra se realiza a primeras horas de la mañana. Las larvas se transportan hacia la laguna en bolsas plásticas con oxigeno, teniendo en cuenta todas las recomendaciones que estos transportes de peces necesitan. Posteriormente son aclimatados en la jaula y transcurrido un tiempo son liberados en el agua.    

# Actividades a desarrollar

1. Evaluar el **impacto Ambiental** del cultivo de pejerrey ( _Odontesthes bonariensis_) en jaulas flotantes en las lagunas seleccionadas. Se tendrá especial atención en la evaluación de la columna de agua asi como de los sedimentos.   


2. Evaluar los **aspectos sociales** de la pesca del pejerrey ( _Odontesthes bonariensis_), este apartado pretende recopilar informacipon sobre la importancia de este pez en el desarrollo de las actividades económicas de la región.   



## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
