---
title: "Producción y contribuciones"
subtitle: ""
author: ""
format: html
---

Esta sección presenta un registro de la producción académica y la trayectoria profesional documentada en fuentes externas. Clic en el link. 

## 1. Publicaciones ##

#### 2026

- Stephanie E. Figary, Michael F. Meyer, Rachel M. Pilla, Warren J. S. Currie, Javier Alcocer, María Belén Alfonso, Caitlin M. Andrews, Orlane Anneville, Ana M. Antão-Geraldes, Shelley E. Arnott, Syuhei Ban, Arnab Banerjee, Gábor Bernáth, Jessica E. Beyer, Kätlin Blank, Kelly L. Bowen, Christer Brönmark, Rosalie Bruel, Sarah H. Burnet, Tyler J. Butts, Cayelan C. Carey, Rossana Caroni, Moitreyee Chakrabarty, Sudeep Chandra, Kirsten S. Christoffersen, Alicia Cortés, Maria Cristina Crispim, Elvira de Eyto, Luciana De Souza Cardoso, Bridget R. Deemer, Curtis L. DeGasperi, Braden C. DeMattei, Jianming Deng, Jean-Pierre Descy, Inta Dimante-Deimantovica, Nadia Diovisalvi, Renata Dondajewska-Pielka, Jonathan P. Doubek, Tvrtko Dražina, Hilary A. Dugan, Zorka Dulić, Ashley A. Dunker, Gaël Dur, Brie A. Edwards, Jolanta E. Ejsmont-Karabin, Mariam Elmarsafy, Zeynep Ersoy, Rocio Fernandez, Heidrun Feuchtmayr, Maria Soledad Fontanarrosa, Elena Forasacco, László G.-Tóth, Evelyn E. Gaiser, Gideon Gal, Anita Galir, Javier R. Garcia de Souza, Scott F. Girdner, Ryszard Goldyn, K. David Hambright, David P. Hamilton, Lars-Anders Hansson, Susan P. Hendricks, Huihuang Chen, Pascal M. Isumbisho, Stéphan Jacquet, Jun Yang, Martin J. Kainz, Maciej Karpowicz, Natalia Kuczyńska-Kippen, Samiullah Khan, Katarzyna Kowalczewska-Madura, Silke Langenheder, Sarah D. Lawhun, Barbara Leoni, Fabio Lepori, Shuqi Lin, Arni H. Litt, Eleanor B. Mackay, Marina M. Manca, Shin-ichiro S. Matsuzaki, Blake Matthews, Linda May, Yvonne R. McElarney, Christopher J. McLimans, Rosemberg F. Menezes, Ewa Merz, Evangelia Michaloudi, S. Jannicke Moe, Dörthe C. Müller-Navarra, Manuel E. Muñoz-Colmenares, Kayden C. Nasworthy, Veronica Nava, Jens C. Nejstgaard, Ulrike Obertegger, David A. Ortiz, Luis A. Oseguera, Michael J. Paterson, Maria Cintia Piccolo, Lorena Pinheiro-Silva, Roberta Piscia, Francesco Pomati, Serena Rasconi, Brian L. Reid, Leonardo L. Ribeiro, Florencia M. Rojas Molina, Joanna Rosinska, Olga O. Rusanovskaya, Nico Salmaso, Jouko Sarvala, S. Geoffrey Schladow, Anna G. Schmidt, Anne E. Scoﬁeld, Facundo Scordo, Jaromír Sed’a, Katie J. Senft, Kirill Shchapov, Svetlana V. Shimaraeva, Eugene A. Silow, Maria Špoljar, Dietmar Straile, Silva M. Sundberg, Jon N. Sweetman, Celia C. Symons, Andrew J. Tanentzap, Barbara Tartarotti, Stephen J. Thackeray, Jan-Erik Thrane, Maxim A. Timofeyev, Jörg Tittel, Pablo Urrutia-Cordero, Piet Verburg, Danielle Machado Vieira, Heather L. Wander, Shohei Watanabe, James M. Watkins, David S. White, Sabine Wollrab, **Vivian Yorojo Moreno**, Horacio E. Zagarese, Matiss Zagars, Petr Znachor. 2026. The Zooplankton International Geospatial dataset: A global repository of spatiotemporal freshwater zooplankton community composition data from lakes and reservoirs to support ecological research. LIMNOLOGY and OCEANOGRAPHY LETTERS. [DOI](http://dx.doi.org/10.1002/lol2.70152) 

- Figary, S.E., M.F. Meyer, R.M. Pilla, W.J. Currie, J. Alcocer, M.B. Alfonso, C.M. Andrews, O. Anneville, A.M. Antão‐Geraldes, S.E. Arnott, S. Ban, A. Banerjee, G. Bernát, J.E. Beyer, K. Blank, K.L. Bowen, C. Brönmark, R. Bruel, S.H. Burnet, T.J. Butts, C.C. Carey, R. Caroni, M. Chakrabarty, S. Chandra, K.S. Christoffersen, A. Cortés, M.C. Crispim, E.d. Eyto, L. De Souza Cardoso, B.R. Deemer, C.L. DeGasperi, B.C. DeMattei, J. Deng, J. Descy, I. Dimante-Deimantovica, N. Diovisalvi, R. Dondajewska-Pielka, J.P. Doubek, T. Dražina, H.A. Dugan, Z. Dulić, A.A. Dunker, G. Dur, B.A. Edwards, J.E. Ejsmont-Karabin, M. Elmarsafy, Z. Ersoy, R. Fernandez, H. Feuchtmayr, M. Soledad Fontanarrosa, E. Forasacco, L. G.‐Tóth, E.E. Gaiser, G. Gal, A. Galir, J.R. Garcia de Souza, S.F. Girdner, R. Goldyn, K. Hambright, D.P. Hamilton, L. Hansson, S.P. Hendricks, H. Chen, P.M. Isumbisho, S. Jacquet, J. Yang, M.J. Kainz, M. Karpowicz, S. Khan, K. Kowalczewska-Madura, N. Kuczyńska-Kippen, S. Langenheder, S.D. Lawhun, B. Leoni, F. Lepori, S. Lin, A.H. Litt, E.B. Mackay, M.M. Manca, S.S. Matsuzaki, B. Matthews, L. May, Y.R. McElarney, C.J. McLimans, R.F. Menezes, E. Merz, E. Michaloudi, S. Moe, D.C. Müller-Navarra, M.E. Muñoz-Colmenares, K.C. Nasworthy, V. Nava, J.C. Nejstgaard, U. Obertegger, D.A. Ortiz, L.A. Oseguera, M.J. Paterson, M.C. Piccolo, L. Pinheiro-Silva, R. Piscia, F. Pomati, S. Rasconi, B.L. Reid, L.L. Ribeiro, F.M. Rojas Molina, J. Rosińska, L.G. Rudstam, J.A. Rusak, O.O. Rusanovskaya, N. Salmaso, J. Sarvala, S. Schladow, A.G. Schmidt, A.E. Scofield, F. Scordo, J. Seďa, K.J. Senft, K. Shchapov, S.V. Shimaraeva, E.A. Silow, M. Špoljar, D. Straile, S.M. Sundberg, J.N. Sweetman, C.C. Symons, A.J. Tanentzap, B. Tartarotti, S.J. Thackeray, J. Thrane, M.A. Timofeyev, J. Tittel, P. Urrutia-Cordero, P. Verburg, D.M. Vieira, H.L. Wander, S. Watanabe, J.M. Watkins, D.S. White, S. Wollrab, <b>V. Yorojo Moreno</b>, H.E. Zagarese, M. Zagars, and P. Znachor. 2026. The Zooplankton International Geospatial (ZIG) dataset: A global repository of spatiotemporal freshwater zooplankton community composition data to support ecological research. Environmental Data Initiative. [published on EDI](https://doi.org/10.6073/pasta/a3b54599e2066b04819df04a24dc9e34) (Accessed 2026-08-16)

- M. Solis, J. Primost, **V. Yorojo**, M. Pantucci, S. Fanelli, H. Mugni, C. Bonetto. 2026. Incorporating native South American aquatic species into acute Species
Sensitivity Distributions: implications for pesticide risk assessment of lambda-cyhalothrin and ammonium glufosinate. Chemosphere. [ENLACE](https://doi.org/10.1016/j.chemosphere.2026.145064)


#### 2025

- Solis Marina, **Vivian Yorojo Moreno**, Luisa Fajardo Gonzalez, Silvia Fanelli, Leticia Peluso and Tomás Mac Loughlin. 2025. Ecological Impact of Pesticides on Aquatic Ecosystems and Their Effect on Invertebrate Communities. In Abstract book SETAC Latin America 16th Biennial Meeting. Embracing Holistic-Dynamic and Science-Driven Environmental Regulations. 

#### 2024

- Ailen SOLANAS, **Vivian YOROJO MORENO**, Javier GARCIA DE SOUZA, Ignacio GARCIA, Silvia PLAUL y Darío COLAUTTI. 2024. Acuicultura de pejerrey (Odontesthes bonariensis) en jaulas flotantes para el aprovechamiento de cavas: evaluación del bombeo de agua como potenciador del cultivo. En libro de resúmenes XII Congreso de Ecología y Manejo de Ecosistemas Acuáticos Pampeanos (XII EMEAP). [PDF](https://iimyc.gob.ar/emeap2024/wp-content/uploads/2024/10/Libro-de-Resumenes-XII-EMEAP-2024.pdf).   

- Tomás MAIZTEGUI, Eliana D. AGRELO, **Vivian YOROJO MORENO** y Darío C.COLAUTTI. 2024. Dinámica espacio-temporal de pescadores recreacionales en el Río de La Plata interno. En libro de resúmenes XII Congreso de Ecología y Manejo de Ecosistemas Acuáticos Pampeanos (XII EMEAP). [PDF](https://iimyc.gob.ar/emeap2024/wp-content/uploads/2024/10/Libro-de-Resumenes-XII-EMEAP-2024.pdf).


#### 2023

- Juan M. Paredes del Puerto, Ariel Paracampo, Ignacio García, Tomás Maiztegui, **Vivian Yorojo Moreno**, Miriam Maroñas, Darío Colautti. 2023. Monitoreo de la ictiofauna en cursos de agua superficial de la cuencia Hidrográfica Matanza-Riachuelo, provincia de Buenos Aires (Argentina). Instituto de Limnología “Dr. R. A. Ringuelet. Convenio Específico Complementario Nro. 8 ACUMAR-ILPLA. [Enlace](http://www.bdh.acumar.gov.ar/bdh3/publicacion_master.php?idobject=513978&retorno=publicacion_listado.php)


- Di Cunzolo, S.; Negri, I.; Solanas, A.; Vojkovic, M.; Garcia de Souza J.;**Yorojo, V.**; Fajardo, L.; Alvarez, M. F.2024. Dinámica del zooplancton en una laguna pampeana en relación al grdo de conectividad hidrica con el Río Salado (BS. AS.).2024. En libro de resúmenes del IV Congreso Iberoamericano de Limnología y X Congreso Argentino de Limnologías (IV CIL, CAL X).[Enlace](https://limnoar.org/)

- Solanas, A.; Vojkovic, M.; Garcia de Souza, J.R.; Benítez, H.H.; **Yorojo, V.**; Maroñas, M.; Plaul, S. E.; Alvarez, M.F.; Colautti, D.C. 2023. Aprovechamiento de pasivos ambientales mediante la acuicultura ecológica de  pejerrey (Odontesthes bonariensis): el caso de una cava de Samborombón (BS. AS.). En libro de resúmenes del IV Congreso Iberoamericano de Limnología y X Congreso Argentino de Limnología (IV CIL, CAL X). [Enlace](https://limnoar.org/)

- Negri, I.; Di Cunzolo, S.; Solanas, A.; Vojkovic, M.; Paredes del Puerto, J.M. ; Maiztegui, T.; **Yorojo, V.**; Alvarez, M. F.; García, I.; Paracampo, A.; Fajardo, L.; Colautti, D.C.; Garcia de Souza J. 2023. ¿Cómo afecta la conectividad hídrica a los ensambles de peces pampeanos? un ejemplo desde la laguna San Lorenzo (BS. AS.). En libro de resúmenes del IV Congreso Iberoamericano de Limnología y X Congreso Argentino de Limnología (IV CIL, CAL X). [Enlace](https://limnoar.org/) 


#### 2022 

- **Yorojo Moreno, V.**; Garcia de Souza, J.R.; Paredes del Puerto, J.M; Sathicq, M.B.; Maroñas, M.E.; Donadelli, J.; Plaul, S.E.; Gómez, N.; Colautti, D.C. 2022. Crecimiento y dieta de pejerrey (Odontesthes bonariensis) criado en jaulas flotantes: en la busqueda de herramientas para optimizar su larvicultura. En libro de resúmenes 7mo Simposio Argentino de Ictiología. [PDF](http://rid.unrn.edu.ar:8080/bitstream/20.500.12049/10868/1/Libro%20de%20Abstracts%20%282%29.pdf)

- **Vivian Yorojo Moreno**, Javier R. Garcia DE Souza, Patricia Riat, Ailen Solanas, Susana Sampietro, Darío C. Colautti. 2022. Acuicultura ecológica del pejerrey (Odontesthes bonariensis): evaluación de la transferencia al sector turístico-pesquero en dos
lagunas pampeanas. XI Congreso de Ecología y Manejo de Ecosistemas Acuáticos Pampeanos (XI EMEAP 2022). [PDF](https://ri.conicet.gov.ar/handle/11336/255114)  


#### 2021

- Garcia de Souza, J. R., **Yorojo Moreno, V.**, Sathicq, M. B., Gómez, N., Sampietro, S., Donadelli, J., & Colautti, D. C. 2021. The performance of ecological cage aquaculture of pejerrey Odontesthes bonariensis in Pampean lakes under two different hydrological scenarios. Aquaculture Research, 52(10), 4829-4840. [Enlace](https://onlinelibrary.wiley.com/doi/abs/10.1111/are.15316)


- JUAN PABLO NOGUEIRAS, SANTIAGO EMANUEL COLINA, NICOLÁS NAHUEL CASTRO, **VIVIAN YOROJO MORENO**, MARÍA SOLEDAD SERENA, MARÍA GABRIELA ECHEVERRÍA Y GERMÁN ERNESTO METZ. 2021. Cultivos celulares primarios de células de pejerrey (Odontesthes bonariensis) para su uso como sustratos en el estudio de virus de interés ictícola. En libro de resúmenes Congreso de Microbiología Veterinaria. Presente y futuro de la Microbiología en Medicina Veterinaria en el marco de "Una Salud". [PDF](https://www.aavld.org.ar/publicaciones/LIBRO-DE-RESUMENES-I-CMV-2021.pdf)



#### 2019

- **Vivian Yorojo Moreno**, Javier R. Garcia de Souza, Miriam E. Maroñas, Juan Martín Paredes del Puerto, Manuel Rodríguez, Patricia Riat, Carolina Monti y Darío C.Colautti. 2019. La acuicultura ecológica del pejerrey en jaulas flotantes como alternativa productiva. En Cortelezzi, A., I. Entraigas, F. Grosman e I. Masson (eds). 2019. Encuentro de saberes para la gestión responsable de ecosistemas acuáticos pampeanos. Azul, Argentina. [Enlace](https://digital.cic.gba.gob.ar/items/9f2398cc-62ed-4fda-9775-502f82bb0cb4)


#### 2017

- **Yorojo Moreno, V.**, García, I., Maroñas, M. E., & Colautti, D. C. 2017. Hábitos alimentarios de Gymnogeophagus meridionalis (Osteichthyes, Cichlidae) en un arroyo urbano. Revista del Museo Argentino de Ciencias Naturales, 19(2), 93-100.[PDF](https://revista.macn.gob.ar/index.php/RevMus/article/view/506/468)

- Garcia de Souza J.R., **Yorojo Moreno Vivian**, Sathicq M.B., Gómez N. & Colautti D.C. 2017. Cultivo extensivo en jaulas flotantes en lagos someros de Argentina: hacia el desarrollo de una acuicultura ecológica. [PDF](https://www.was.org/LACC/_downloads/LacQua17_AbstractBook.pdf)


## 2. Menciones destacadas ##

- Age and growth of Pseudoplatystoma corruscans (Siluriformes: Pimelodidae) at the confluence of the Paraná and Paraguay rivers
    - Autores: Balboni, L., Vargas, F., & Colautti, D.
    - Publicación: Neotropical Ichthyology, 19(2), e200101. (2021)
    - Mi Contribución: Mención en agradecimientos por el soporte en las estimaciones con el software R.
    - Enlace directo: [PDF](https://www.scielo.br/j/ni/a/n49HtTKwRVk4GBTGbrnpd7B/?format=pdf&lang=en)  


## 3. Roles y trayectoria   

- Publicación: **International Zoo Yearbook**, Volumen 43
  - Fecha: 2009
  - Detalle del reconocimiento: Listada en el directorio internacional de funcionarios de zoológicos y acuarios, documentando mi cargo oficial en la Fundación Zoologica de Cali.
  - Referencia DOI: 10.1111/j.1748-1090.2008.00081.x
  - Enlace: [Enlace](https://zslpublications.onlinelibrary.wiley.com/doi/abs/10.1111/j.1748-1090.2008.00081.x)


- Publicación: **International Zoo Yearbook**, Volumen 42
  - Fecha: 2008
  - Detalle del reconocimiento: Listada en el directorio intrnacional de funcionarios de zoológicos y acuarios, documentando mi cargo oficial en la Fundación Zoologica de Cali.
  - Referencia DOI: 10.1111/j.1748-1090.2008.00081.x
  - Enlace: [Enlace](https://zslpublications.onlinelibrary.wiley.com/doi/abs/10.1111/j.1748-1090.2008.00056.x)

