---
title: "Participación en proyectos"
---

En esta sección se encuentran algunos proyectos de investigación aplicada en los que he participado. Los documentos que están publicados en internet tienen enlace. 


## Colaboraciones técnicas y campañas de campo

#### 📊 **Zooplankton as Indicators Group (ZIG)**
* **Proyecto marco:** grupo de trabajo internacional asociado a GLEON (Global Lake Ecological Observatory Network) dedicado a compilar bases de datos globales de zooplancton de agua dulce. Su objetivo es utilizar estos pequeños organismos como indicadores ecológicos para entender cómo responden los ecosistemas a los cambios ambientales. 
* **Rol:** Data Harmonization Team. **Contribución:** participación en la armonización de datos de zooplancton de agua dulce a nivel global, contribuyendo a la creación de bases de datos estandarizadas que facilitan el análisis comparativo y la investigación ecológica a gran escala.
* **Habilidad clave:** manejo del software R y Rstudio.
* **Link de referencia:** [ZIG Data Harmonization Team](https://sfigary.github.io/website/ZIG.html)

---

#### 🚢 **Caracterización biológica y ecológica de una laguna pampeana**

* **Proyecto marco:** relevamiento ambiental e ictiológico de laguna Chís Chís.
* **Rol:** miembro del equipo de campo. **Contribución:** recolección en campo de muestras de peces y zooplancton. Documentación de parámetros biológicos para el análisis poblacional y pesquero. 
* **Habilidad clave:** evaluación de zooplancton en cuerpos de agua. Análisis estadístico en software R. 

---


#### 🐟 **Proyecto producción de juveniles en la laguna Chis chis**

* **Proyecto marco:** producción masiva de juveniles de pejerrey (Odontesthes bonariensis) utilizando jaulas flotantes en lagunas del partido de Lezama, Provincia de Buenos Aires.
* **Rol:** miembro del equipo de campo. **Contribución:** miembro responsable del proceso de implementación del cultivo. 
* **Habilidad clave:** técnicas de acuicultura ecológica en jaulas flotantes. 


---


#### 🔬 **Estudio limnológico del Embalse del Rio III**

* **Proyecto marco:**  Estudio limnológico del Embalse del Rio III, Córdoba (Argentina). Contrato nucleoeléctrica Argentina SA.-ILPLA, FCNyM, UNLP – CONICET Ref.: N.A.S.A. OC Nº 4500119836
* **Rol:** miembro del equipo trabajo. **Contribución:** determinación taxonómica, cuantificación, análisis y presentación de informe. 
* **Habilidad clave:** evaluación de zooplancton en cuerpos de agua. Manejo de software R. 



---

#### 🚢 **Campaña de muestreo biológico pesquero**

* **Proyecto marco:** proyecto de evaluación biológica y pesquera de especies de interés deportivo y comercial (EBIPES).
* **Rol:** miembro del equipo de campo en la campaña N° 65. **Contribución:** recolección en campo de muestras de peces y en la documentación de parámetros biológicos (determinación de sexo y otros datos morfométricos) esenciales para el análisis poblacional y pesquero.
* **Habilidad clave:** Muestreo ictiológico en campo, recolección estandarizada de muestras y determinación de parámetros biológicos.
* **Documento de referencia:** [Informe técnico N°84 - Campaña 65 (2024)]. [Enlace](https://www.magyp.gob.ar/sitio/areas/pesca_continental/informes/proyecto_ebipes/_archivos//000000_Informes%20del%20proyecto%20evaluaci%C3%B3n%20biol%C3%B3gica%20y%20pesquera%20de%20especies%20de%20inter%C3%A9s%20deportivo%20y%20comercial/240812_Informe%20T%C3%A9cnico%20N%C2%B0%2084%20-%20Informe%20Biologico%20de%20la%20Campa%C3%B1a%2065.pdf)

---



#### 🔬 **Caracterización limnológica de una laguna pampeana**

* **Proyecto marco:** Estudio limnológico de la laguna De Bragado.
* **Rol:**  análisis de muestras de zooplancton. **Contribución:** cuantíficación y determinación taxonómica de zooplancton. 
* **Habilidad clave:** evaluación de zooplancton en cuerpos de agua. 


---



#### 🔬 **Caracterización biológica y ecológica de una laguna pampeana**

* **Proyecto marco:** Estudio ictiológico y limnológico de la laguna San Lorenzo.
* **Rol:**  miembro del equipo de campo. **Contribución 1:** recolección en campo de muestras de peces y zooplancton, y en la documentación de parámetros biológicos para el análisis poblacional y pesquero. **Contribución 2:** cuantíficación y determinación taxonómica de zooplancton. 
* **Habilidad clave:** evaluación de zooplancton en cuerpos de agua. 

---



#### 🐟 **Taller de determinación de edades en peces (otolitometría aplicada)**

* **Proyecto marco:** evaluación de los recursos ícticos del bajo río Uruguay y del Río de la Plata Interior (CARU-CARP).
* **Rol:** participación activa en el IV Taller de preparación y lectura de otolitos. **Contribución:** responsable de la determinación de edades en ejemplares de peces, actividad que está directamente vinculada a la evaluación demográfica y pesquera del recurso ictícola regional.
* **Habilidad clave:** Técnicas de preparación y lectura de otolitos (Otolitometría).
* **Documento de referencia:** [Informe Técnico Campaña Invierno 2016]. [Enlace](https://www.magyp.gob.ar/sitio/areas/pesca_continental/informes/proyectos_caru/_archivos/000000_Informes%20Proyectos%20CARU/180227_Informe%20CARU-CARP%20Campa%C3%B1a%20de%20Invierno%202016.pdf)

---
